#!/usr/bin/env bash
set -euo pipefail
# ══════════════════════════════════════════════════════════════════════════════
# Detect host OS and firewall backend, persist to .firewall.conf
# Called by: make init (via scripts/setup.sh)
# ══════════════════════════════════════════════════════════════════════════════

BOLD='\033[1m'
DIM='\033[2m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m'

CONF_FILE="${1:-.firewall.conf}"

# ── Detect OS ─────────────────────────────────────────────────────────────────
detect_os() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        echo "$ID"
    elif command -v lsb_release &>/dev/null; then
        lsb_release -si | tr '[:upper:]' '[:lower:]'
    else
        echo "unknown"
    fi
}

# ── Detect firewall backend ──────────────────────────────────────────────────
detect_backend() {
    # Check for firewalld (Fedora, CentOS, RHEL, etc.)
    if command -v firewall-cmd &>/dev/null && systemctl is-active firewalld &>/dev/null 2>&1; then
        echo "firewalld"
        return
    fi

    # Check for ufw (Ubuntu, Debian, etc.)
    if command -v ufw &>/dev/null; then
        echo "ufw"
        return
    fi

    echo "manual"
}

# ── Detect firewalld zone ────────────────────────────────────────────────────
detect_firewalld_zone() {
    if command -v firewall-cmd &>/dev/null; then
        firewall-cmd --get-default-zone 2>/dev/null || echo "public"
    else
        echo "public"
    fi
}

# ── Check if Caddy is configured ─────────────────────────────────────────────
detect_caddy() {
    if [ -f caddy/Caddyfile ] && grep -q "reverse_proxy" caddy/Caddyfile 2>/dev/null; then
        echo "true"
    else
        echo "false"
    fi
}

# ── Interactive mode ──────────────────────────────────────────────────────────
run_interactive() {
    local os backend zone caddy_enabled

    os=$(detect_os)
    backend=$(detect_backend)
    zone=""
    caddy_enabled=$(detect_caddy)

    echo ""
    echo -e "${BOLD}── Firewall Configuration ──${NC}"
    echo ""

    if [ "$backend" != "manual" ]; then
        echo -e "  Detected OS:       ${GREEN}${os}${NC}"
        echo -e "  Detected backend:  ${GREEN}${backend}${NC}"
        if [ "$backend" = "firewalld" ]; then
            zone=$(detect_firewalld_zone)
            echo -e "  Detected zone:     ${GREEN}${zone}${NC}"
        fi
        echo ""
        echo -ne "  Use detected firewall backend? ${DIM}[Y/n]${NC}: "
        read -r use_detected || true
        if [ "${use_detected,,}" = "n" ]; then
            backend=""
        fi
    else
        echo -e "  Detected OS: ${YELLOW}${os}${NC}"
        echo -e "  ${YELLOW}Could not auto-detect a supported firewall backend.${NC}"
        echo ""
    fi

    if [ -z "$backend" ] || [ "$backend" = "manual" ]; then
        echo ""
        echo "  Select firewall backend:"
        echo "    1) firewalld  (Fedora, CentOS, RHEL)"
        echo "    2) ufw        (Ubuntu, Debian)"
        echo "    3) manual     (manage firewall yourself)"
        echo -ne "  ${DIM}[3]${NC}: "
        read -r fw_choice || true
        fw_choice="${fw_choice:-3}"
        case "$fw_choice" in
            1) backend="firewalld" ;;
            2) backend="ufw" ;;
            *) backend="manual" ;;
        esac

        if [ "$backend" = "firewalld" ]; then
            zone=$(detect_firewalld_zone)
            echo -ne "  firewalld zone ${DIM}[${zone}]${NC}: "
            read -r zone_input || true
            zone="${zone_input:-$zone}"
        fi
    fi

    if [ "$backend" = "manual" ]; then
        echo ""
        echo -e "  ${YELLOW}Manual mode: firewall commands will print guidance instead of running.${NC}"
        echo -e "  ${DIM}See docs/firewall-manual.md for instructions.${NC}"
    fi

    # Write config
    write_config "$os" "$backend" "$zone" "$caddy_enabled"

    echo ""
    echo -e "  Firewall config saved to ${GREEN}.firewall.conf${NC}"
}

# ── Write config file ────────────────────────────────────────────────────────
write_config() {
    local os="$1" backend="$2" zone="$3" caddy_enabled="$4"

    cat > "$CONF_FILE" <<EOF
# Auto-generated by make init — safe to edit
# Re-run 'make init' or edit manually to change settings
FIREWALL_BACKEND=${backend}
FIREWALL_OS=${os}
FIREWALL_ZONE=${zone}
CADDY_ENABLED=${caddy_enabled}
EOF
}

# ── Silent mode (re-detection without prompts) ───────────────────────────────
run_silent() {
    local os backend zone caddy_enabled
    os=$(detect_os)
    backend=$(detect_backend)
    zone=""
    if [ "$backend" = "firewalld" ]; then
        zone=$(detect_firewalld_zone)
    fi
    caddy_enabled=$(detect_caddy)
    write_config "$os" "$backend" "$zone" "$caddy_enabled"
}

# ── Entry point ───────────────────────────────────────────────────────────────
if [ "${2:-}" = "--silent" ]; then
    run_silent
else
    run_interactive
fi
